import React, { useState, useEffect, useRef, LinkProps } from "react";
import { Form, Text } from "informed";
import { Link, withRouter, useHistory, useNavigate } from "react-router-dom";
const { GoogleSpreadsheet } = require('google-spreadsheet');

const SPREADSHEET_ID = "1aj3fhDrOp1M_Qww8n8CC_TziNiYyhyifPKGGKSeNaUw"; //from the URL of your blank Google Sheet
const CLIENT_ID =
  "366890563540-41bike67bihilkifa0rscek54g3cmkt4.apps.googleusercontent.com"; //from https://console.developers.google.com/apis/credentials
const API_KEY = "AIzaSyApqrQ8aXiKeZbRkAxnhSY1eE-CROieVIU"; //https://console.developers.google.com/apis/credentials
const SCOPE = "https://www.googleapis.com/auth/spreadsheets";

const EarnToWinRaffle = ({ props, ref, currentRoute }) => {

  useEffect(() => {
    document.title = "Black Spot Studio | Earn to win raffle";
  }, []);
  const doc = new GoogleSpreadsheet('<the sheet ID from the url>');

  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info

    client_email: "form-submission@black-spot-studio-ph.iam.gserviceaccount.com",
    private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCqH42S6WbnfRzK\nVjvN1OfrTt90Ku/pbQ3W5OaB22ZYhYOVbgszme4bCAVfiBaA7WbDtqlwi4EDuwGG\nMwJaAkHOlugyw6z2uy2Ftt6EEuiTQohkSurIZohvvObAQOgSWR4riTkRPB5q5dts\nadnlWXpmIH05vDA6OvqSV/zo7o9fypIhnxrwYdbj4RMRf7zDijbjTYwybr1/9USq\n30KPdVq8m0vnrzkitp5cx0HYVcH+zBeCABlavMhRwm+I1947tfRy7JuxIQLBE0YJ\nnKuRIQxb8UiQ7z6kisqhGKBMK1+GllwCH2/ZclGap40HngntuUOaAO75XtUNV7+i\njplc2ZhzAgMBAAECggEAFdVIgJnBcfpoZv6r3IMzTnYyuascW3tPouGBRG9+vOP0\nWrRNmLjryilR3eGjwwvKEVplzYKsiJOH+GFJ2c5fWV7xpuOI/6ikXib1e21yeW+4\n/GdxpqLOEMplXOLCReniXtj/a3BT67PbNhiG9TxyDR2kpJ5mcXAJ93J2YViN1aT+\nr3BiPt+0FxURtDb39n4i2XdC5kvj/b1iJvH97SN4oc7F47kWsDoQZ0SoVjzhOtXn\nMfcnzc1eXNzpUj63Zb5WadLxmXwAdkAUbWI5BME5fekc4DRcHetWdzMTBDRbIs6c\n4/yjolUuLqWdb5dcR2KPglnXIMR6Su0mlSLRgglZ9QKBgQDX+QOHp9vcY+Gp9ugC\nxKTpc0McC/KfgNIRDPiuhirmNeEeVKcclpdBNmPdEkMPwh0wxCFCyg40WqCW043r\n6k52V2UeOj+JSIMAF2tTs1VjpZpisVjNPcOJ1jyOI7cAqdJ9Z0IuL8KBeSBFbT6E\n4d0YvTsV+HDEg9BLR8iIRc22xwKBgQDJpy14Gvx14KfN6ZqwUWMOuCCVxhEnLKoy\no0yCqbjTlR3eQskNz7SC02pR5qOXnlNv+cZftdCYrRDToCEDwnM2DFnEGHEnWCwd\ndgKzm+wwSM8W+pKvM0PkCjADtlhmF1vZskzA4pBXPFL92RmGFsQzmbmP2vYzF1Ta\nUyb6iRz09QKBgQCEv/fuezwGFJLR4QUtJmfjYsi+RY3Fgu4cMufshmV6CWYtOYVa\naingmKj7as0zs3Iz1mpHXmEqxwXsj26tsuC1lvR9hvokzSBQfxSmZxW2YUUrIq1d\nwngdkkS4bbV/v+K02DJyp0KcSLKQWhzSmu5G1ZGq6IGQGSGAFEhrktRmYwKBgQCG\nKd87oKDFgKHEgx7zHkMMoP61B2GUMchPBoy6Ble9FeIYZVDFCqMrw6NiOFQxZRpY\nTtNoDFxrqAGg+1Hb4Xyrwg3bRPPL3IMFWuWzQBMlkNuPi0kanb4Ws5x8a85mpjXr\nIhCk6FhmYfFJiS7NIsqJFkb6ahERrv06gMZXO/BzHQKBgQCdpjy3owBLKpPEYXGQ\n2boZ/Untjsh1jii91s7I5jToetdy+FDRf1GJEjOiynso6ErpSt+VedgqIljfSnbg\nZxQgEbUBJxUpqSKEGHwhBLu3MiT9eF1676jhB1ENgiZYnkW41COEMTzFDG8WlYNX\nr5KZpsFQ9Ue65zp1rxjjbcohCw==\n-----END PRIVATE KEY-----\n",
  });
  return (
    <div className="register wrapper">
      <div className="register-wrapper">
        <div className="form-wrapper">
          <h1>Gogo Racing Info</h1>
          <form method="get" id="formwrap" onSubmit={this.onFormSubmit}>
            <input
              type="text"
              autoComplete="off"
              name="name"
              placeholder="Enter your Account Name"
              required
            />
            <input
              type="text"
              autoComplete="off"
              name="number"
              placeholder="Enter Your Account ID"
              maxLength="6"
              required
            />
            <input
              type="email"
              autoComplete="off"
              name="email"
              placeholder="Enter Your Email"
              required
            />
            <div className="down-buddeh">
              <div className="up">
                <input type="checkbox" name="check" id="check" required />
                <label htmlFor="check" id="checksz">
                  I have read and agree to the terms and conditions and privacy
                  policy.
                </label>
              </div>
              <div className="down">
                <input type="checkbox" name="check2" id="check2" required />
                <label htmlFor="check2" id="checksz">
                  Sign up to our newsletter to receive our latest news and
                  offers
                </label>
              </div>
            </div>
            <button type="submit">Submit</button>
          </form>
        </div>
      </div>
    </div>
  );
};

export default EarnToWinRaffle;
